### ISSUE TITLE
Support for Teensy 4.0 multiple i2c

### ISSUE THREAD

**Issue by DennisSchm** [RobTillaart/PCF8575#29]
Hello and thank you for this great library. 

I'd like to why your library does not allow for constructors passing the **Wire** address when **TEENSYDUINO** is defined. 
I am using the teensy 4.0 which has more than one wire but without modification of the library I could only use the default wire. This should be a fairly easy change to do if I don't miss something. 

Thank you for your time, 
Dennis

**Comment by RobTillaart** [comment]
Good morning, 
The reason is that my library development process is evolutionary. They grow on request if the request is generic enough. Some requests make sense for multiple libraries so if time permits I add them to those that apply. This request makes sense for at least PCF8574 and possibly all I2C based libraries.

I will dive into this asap. As I do not have all boards I hope you can do the testing.

**Comment by RobTillaart** [comment]
@DennisSchm 

> without modification of the library I could only use the default wire.

1. Can you post that modification?
2. Can you post a minimal sketch showing how you call

**Comment by RobTillaart** [comment]
@DennisSchm 

Installed **TEENSYDUINO** in my 1.8.19 IDE and **PCF8575_Wire2.ino** test sketch compiles.
Cannot test it as I have no teensy 4.0

**Comment by RobTillaart** [comment]
Wrong library error => continues in #30
